version: '2'

services:
  app_api:
    build:
      context: ./
      dockerfile: api.dockerfile
    working_dir: /var/www/api
    volumes:
      - ./code/api:/var/www/api
    links:
      - db
  app_client:
    build:
      context: ./
      dockerfile: client.dockerfile
    working_dir: /var/www/client
    volumes:
      - ./code/web:/var/www/client
    links:
      - app_api
  nginx:
    image: nginx:latest
    volumes:
      - ./code/web:/var/www/web
      - ./code/api:/var/www/api
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8088:80
      - 8089:81
    links:
      - app_api
      - app_client
  db:
    image: mysql:5.6
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33366:3306"

