version: '2'

services:
  app_api:
    build:
      context: ./
      dockerfile: api.dockerfile
    working_dir: /var/www/api
    volumes:
      - ./code/api:/var/www/api
    links:
      - db
  app_client:
    build:
      context: ./
      dockerfile: client.dockerfile
    working_dir: /var/www/client
    volumes:
      - ./code/client:/var/www/client
    links:
      - app_api
  nginx:
    image: nginx:latest
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./code/api:/var/www/api
      - ./code/client:/var/www/client
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 80:80
    links:
      - app_api
      - app_client
  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33366:3306"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      links:
        - db
      ports:
        - 8181:80
      environment:
        MYSQL_USERNAME: admin
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: db
